version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "127.0.0.1:50000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./app:/code

  db:
    image: mysql:5.7
    ports:
      - "127.0.0.1:32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
